### ISSUE TITLE
Simultaneous converts from different threads crash #52

### ISSUE THREAD

**Issue by limayesn** [tuespetre/TuesPechkin#100] opened 2015-04-27 09:08 UTC
Hi,
    I am using this library with great effect for html to pdf conversion in ASP.Net web application. However, I am facing same issue that is mentioned in #52. If simultaneous conversions are in process, one user has to wait until other conversion is completed. Is this issue resolved? Can we handle it from .net code behind where conversion code is placed?

Thanks
limayesn

**Comment by tuespetre** [comment] 2015-04-27 13:48
See: https://github.com/tuespetre/TuesPechkin/issues/63

I should be able to do some stuff 'underneath' the public interface that will allow multiple copies of wkhtmltox to work simultaneously but it's a matter of finding the time to do it. I'm sorry this is not in place yet. For now, only one conversion may run at a time and the threads will queue up and wait for their turn.

I will close your issue as it is really a duplicate of the one linked above.

**Closed as completed by tuespetre** 2015-04-27 13:48 UTC

**Comment by tuespetre** [comment] 2015-04-27 13:52
BTW here is some information about what needs to be done if you think you can help!

http://stackoverflow.com/questions/1202744/dynamically-p-invoking-a-dll

**Comment by limayesn** [comment] 2015-04-27 14:02
Thanks Tuespetre. Yes, i will check out the link given by you.
BTW, the best html to pdf conversion i have found!!! Amazing work!

**Comment by tuespetre** [comment] 2015-04-27 14:20
Thanks; credit really belongs here: https://github.com/wkhtmltopdf/wkhtmltopdf
