### ISSUE TITLE
Requirement of having multiple converter

### ISSUE THREAD

**Issue by m-arabi** [tuespetre/TuesPechkin#111] opened 2015-06-24 09:50 UTC
Hi,

I am using this library for converting html to both PDF and Image in Web / Win project.
I have defined the converters as static as below

```
static string tempPathPDF = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "wkhtml_PDF");
        static string tempPathImage = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "wkhtml_Image");
        private static IConverter pdfConverter = new ThreadSafeConverter(new PdfToolset(new Win64EmbeddedDeployment(new StaticDeployment(tempPathPDF))));
        private static IConverter imageConverter = new ThreadSafeConverter(new ImageToolset(new Win64EmbeddedDeployment(new StaticDeployment(tempPathImage))));
```

What happens is, when I invoke PDF converter, I am able to generate n number of PDF sequentially or in threaded fasion. But if I invoke the image converter in between. It does not respond, or the thread does not return and output.

Any help is this regards is much appreciated. Advance thanks for the reply.

Arabi

**Comment by tuespetre** [comment] 2015-07-17 02:55
Duplicate of https://github.com/tuespetre/TuesPechkin/issues/63

I hope to find some time for further development on this project in the coming weeks, but we all know how that goes. In the meantime you may consider creating a separate worker process to perform conversions, using message queuing or similar to achieve inter-process communication.

**Closed as completed by tuespetre** 2015-07-17 02:55 UTC
